### PR TITLE
API26 support

### PR DESCRIPTION
**Pull request by boswelja**
* Fix adaptive icon support by making a new method that gets called if we're running API26 a.k.a O when generating the Overview titlebar color, this fixes a ClassCastException as we cannot cast AdaptiveIconDrawable to BitmapDrawable

### CODE REVIEW

**Comment by boswelja** [comment]
#37

**Comment by boswelja** [comment]
Tested adaptive icon fix on Android O, working fine. Probably needs to be tested on versions less than O to be sure I haven't broken anything

**Comment by afollestad** [comment]
Looks like the build is failing on Travis.ci

**Comment by boswelja** [comment]
It's failing because the master travis.yml is still fetching api25 stuff, assuming it supports it, my changes will make it sync api26

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by afollestad** [comment]
It looks like it's actually unable to find 3.0.0-alpha3 of the Gradle plugin also. 

You'll probably need to merge the master branch into this one too

**Comment by boswelja** [comment]
That's strange as to why it cannot find the new Gradle plugin.. Android studio has no problem with it

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by boswelja** [comment]
I just went to merge the master branch.. Looks like you beat me to it lol

**Comment by boswelja** [comment]
@afollestad I got travis passing :D

**Pull request merged**
